name: Docker-CI
trigger:
  - main

pool:
  vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds

variables:
  imageName: 'nero20052023/bellyfood-backend'

steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: $(imageName)
      command: build
      Dockerfile: ./Dockerfile
  - task: Docker@2
    displayName: Push image
    inputs:
      containerRegistry: 'Docker Hub'
      repository: $(imageName)
      command: push
      tags: 'latest'